/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.ulbra.view;

import br.ulbra.controller.JogoController;
import br.ulbra.model.Jogo;

/**
 *
 * @author s.lucas
 */
public class FRTelaJogo extends javax.swing.JDialog {

    /**
     * Creates new form FRTelaJogo
     */
    public FRTelaJogo(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        this.setLocationRelativeTo(null);
    }
    private int pkJogo;

    public void setPkJogo(int pkJogo) {
        this.pkJogo = pkJogo;
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btVoltar3 = new javax.swing.JButton();
        lbFoto = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtGenero = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtProdutora = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtDataLan = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtCodigo = new javax.swing.JTextField();
        txtNome = new javax.swing.JTextField();
        txtClassfi1 = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        btAlterar = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtDescricao = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("[ULBRA] - Detalhes do Jogo");
        setMinimumSize(new java.awt.Dimension(996, 669));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(84, 84, 84));
        jPanel1.setLayout(null);

        btVoltar3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/ulbra/img/back.png"))); // NOI18N
        btVoltar3.setText("Voltar");
        btVoltar3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btVoltar3MouseClicked(evt);
            }
        });
        btVoltar3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btVoltar3ActionPerformed(evt);
            }
        });
        jPanel1.add(btVoltar3);
        btVoltar3.setBounds(370, 576, 149, 55);

        lbFoto.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        jPanel1.add(lbFoto);
        lbFoto.setBounds(573, 23, 200, 300);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Gênero");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(573, 341, 50, 17);

        txtGenero.setEditable(false);
        txtGenero.setBackground(new java.awt.Color(84, 84, 84));
        txtGenero.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtGenero.setForeground(new java.awt.Color(255, 255, 255));
        txtGenero.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 1, true));
        txtGenero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtGeneroActionPerformed(evt);
            }
        });
        jPanel1.add(txtGenero);
        txtGenero.setBounds(573, 364, 401, 28);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Produtora");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(573, 410, 71, 17);

        txtProdutora.setEditable(false);
        txtProdutora.setBackground(new java.awt.Color(84, 84, 84));
        txtProdutora.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtProdutora.setForeground(new java.awt.Color(255, 255, 255));
        txtProdutora.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 1, true));
        txtProdutora.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtProdutoraActionPerformed(evt);
            }
        });
        jPanel1.add(txtProdutora);
        txtProdutora.setBounds(573, 433, 401, 28);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Data de Lançamento");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(791, 130, 183, 17);

        txtDataLan.setEditable(false);
        txtDataLan.setBackground(new java.awt.Color(84, 84, 84));
        txtDataLan.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtDataLan.setForeground(new java.awt.Color(255, 255, 255));
        txtDataLan.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 1, true));
        txtDataLan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDataLanActionPerformed(evt);
            }
        });
        jPanel1.add(txtDataLan);
        txtDataLan.setBounds(791, 165, 183, 28);

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("ID");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(791, 23, 17, 17);

        txtCodigo.setEditable(false);
        txtCodigo.setBackground(new java.awt.Color(84, 84, 84));
        txtCodigo.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtCodigo.setForeground(new java.awt.Color(255, 255, 255));
        txtCodigo.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 1, true));
        txtCodigo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCodigoActionPerformed(evt);
            }
        });
        jPanel1.add(txtCodigo);
        txtCodigo.setBounds(791, 58, 183, 28);

        txtNome.setEditable(false);
        txtNome.setBackground(new java.awt.Color(84, 84, 84));
        txtNome.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        txtNome.setForeground(new java.awt.Color(255, 255, 255));
        txtNome.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 1, true));
        txtNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNomeActionPerformed(evt);
            }
        });
        jPanel1.add(txtNome);
        txtNome.setBounds(32, 23, 487, 28);

        txtClassfi1.setEditable(false);
        txtClassfi1.setBackground(new java.awt.Color(84, 84, 84));
        txtClassfi1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtClassfi1.setForeground(new java.awt.Color(255, 255, 255));
        txtClassfi1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 1, true));
        txtClassfi1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtClassfi1ActionPerformed(evt);
            }
        });
        jPanel1.add(txtClassfi1);
        txtClassfi1.setBounds(791, 295, 183, 28);

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Classificação Indicativa");
        jPanel1.add(jLabel9);
        jLabel9.setBounds(791, 260, 183, 17);

        btAlterar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/ulbra/img/lapis2.png"))); // NOI18N
        btAlterar.setText("Alterar");
        btAlterar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btAlterarMouseClicked(evt);
            }
        });
        btAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAlterarActionPerformed(evt);
            }
        });
        jPanel1.add(btAlterar);
        btAlterar.setBounds(573, 576, 144, 55);

        txtDescricao.setEditable(false);
        txtDescricao.setBackground(new java.awt.Color(84, 84, 84));
        txtDescricao.setColumns(20);
        txtDescricao.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        txtDescricao.setForeground(new java.awt.Color(255, 255, 255));
        txtDescricao.setLineWrap(true);
        txtDescricao.setRows(5);
        txtDescricao.setBorder(null);
        jScrollPane2.setViewportView(txtDescricao);

        jPanel1.add(jScrollPane2);
        jScrollPane2.setBounds(32, 69, 487, 489);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/ulbra/img/fundo4.jpg"))); // NOI18N
        jPanel1.add(jLabel1);
        jLabel1.setBounds(0, 560, 990, 110);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/ulbra/img/fundo4.jpg"))); // NOI18N
        jPanel1.add(jLabel2);
        jLabel2.setBounds(0, 0, 990, 560);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 992, 669);

        pack();
    }// </editor-fold>//GEN-END:initComponents
 
    private void btVoltar3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btVoltar3MouseClicked
        this.dispose();
    }//GEN-LAST:event_btVoltar3MouseClicked

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
         
        JogoController controller = new JogoController();
        Jogo jg = controller.readForPk(pkJogo);

        String codigo = String.valueOf(jg.getPk_jogo());
        txtCodigo.setText(codigo);
        txtNome.setText(jg.getNomeJogo());
        txtGenero.setText(jg.getGeneroJogo());
        txtProdutora.setText(jg.getProdutoraJogo());
        txtDataLan.setText(jg.getDataLanJogo());
        txtClassfi1.setText(jg.getClassfiJogo());
        txtDescricao.setText(jg.getDescricaoJogo());
        lbFoto.setIcon(jg.getImagemJogo());

    }//GEN-LAST:event_formWindowActivated

    private void txtGeneroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtGeneroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtGeneroActionPerformed

    private void txtProdutoraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtProdutoraActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtProdutoraActionPerformed

    private void txtDataLanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDataLanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDataLanActionPerformed

    private void txtCodigoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCodigoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCodigoActionPerformed

    private void txtNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNomeActionPerformed

    private void txtClassfi1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtClassfi1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtClassfi1ActionPerformed

        public void carregar(){
        JogoController controller = new JogoController();
        Jogo jg = controller.readForPk(pkJogo);

        String codigo = String.valueOf(jg.getPk_jogo());
        txtCodigo.setText(codigo);
        txtNome.setText(jg.getNomeJogo());
        txtGenero.setText(jg.getGeneroJogo());
        txtProdutora.setText(jg.getProdutoraJogo());
        txtDataLan.setText(jg.getDataLanJogo());
        txtClassfi1.setText(jg.getClassfiJogo());
        txtDescricao.setText(jg.getDescricaoJogo());
        lbFoto.setIcon(jg.getImagemJogo());
    }
        
    private void btAlterarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btAlterarMouseClicked
        
    }//GEN-LAST:event_btAlterarMouseClicked
        
    private void btVoltar3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btVoltar3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btVoltar3ActionPerformed

    private void btAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAlterarActionPerformed
        FRUpDelJogo upDelJogo = new FRUpDelJogo(null, rootPaneCheckingEnabled);
        
        upDelJogo.setPkJogo(pkJogo);
        upDelJogo.carregar();
        upDelJogo.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btAlterarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FRTelaJogo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FRTelaJogo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FRTelaJogo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FRTelaJogo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                FRTelaJogo dialog = new FRTelaJogo(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btAlterar;
    private javax.swing.JButton btVoltar3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lbFoto;
    private javax.swing.JTextField txtClassfi1;
    private javax.swing.JTextField txtCodigo;
    private javax.swing.JTextField txtDataLan;
    private javax.swing.JTextArea txtDescricao;
    private javax.swing.JTextField txtGenero;
    private javax.swing.JTextField txtNome;
    private javax.swing.JTextField txtProdutora;
    // End of variables declaration//GEN-END:variables
}
