/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.ulbra.view;

import br.ulbra.controller.JogoController;
import br.ulbra.model.Jogo;
import br.ulbra.utils.Utils;
import java.io.File;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

/**
 *
 * @author s.lucas
 */
public class FRUpDelJogo extends javax.swing.JDialog {

    /**
     * Creates new form FRUpDelJogo
     */
    public FRUpDelJogo(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        this.setLocationRelativeTo(null);
    }
    private int pkJogo;
    
    public void setPkJogo(int pkJogo){
        this.pkJogo = pkJogo;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtNome = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtGenero = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtProdutora = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtDataLan = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtClassfi = new javax.swing.JTextField();
        btVoltar = new javax.swing.JButton();
        btEscolherImagem = new javax.swing.JButton();
        lbFoto = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtCodigo = new javax.swing.JTextField();
        btExcluir2 = new javax.swing.JButton();
        btAlterar = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtDescricao = new javax.swing.JTextArea();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("[ULBRA] - Atualização do Jogo");
        setMinimumSize(new java.awt.Dimension(1368, 734));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(84, 84, 84));
        jPanel1.setLayout(null);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/ulbra/img/nuvem.png"))); // NOI18N
        jPanel1.add(jLabel1);
        jLabel1.setBounds(96, 33, 64, 64);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Atualização do Jogo");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(187, 44, 363, 44);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("ID");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(96, 152, 17, 17);

        txtNome.setBackground(new java.awt.Color(51, 51, 51));
        txtNome.setForeground(new java.awt.Color(255, 255, 255));
        txtNome.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 1, true));
        txtNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNomeActionPerformed(evt);
            }
        });
        jPanel1.add(txtNome);
        txtNome.setBounds(96, 237, 454, 28);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Gênero");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(96, 277, 50, 17);

        txtGenero.setBackground(new java.awt.Color(51, 51, 51));
        txtGenero.setForeground(new java.awt.Color(255, 255, 255));
        txtGenero.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 1, true));
        txtGenero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtGeneroActionPerformed(evt);
            }
        });
        jPanel1.add(txtGenero);
        txtGenero.setBounds(96, 300, 454, 28);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Produtora");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(96, 346, 71, 17);

        txtProdutora.setBackground(new java.awt.Color(51, 51, 51));
        txtProdutora.setForeground(new java.awt.Color(255, 255, 255));
        txtProdutora.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 1, true));
        txtProdutora.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtProdutoraActionPerformed(evt);
            }
        });
        jPanel1.add(txtProdutora);
        txtProdutora.setBounds(96, 369, 454, 28);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Data de Lançamento");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(96, 415, 142, 17);

        txtDataLan.setBackground(new java.awt.Color(51, 51, 51));
        txtDataLan.setForeground(new java.awt.Color(255, 255, 255));
        txtDataLan.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 1, true));
        txtDataLan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDataLanActionPerformed(evt);
            }
        });
        jPanel1.add(txtDataLan);
        txtDataLan.setBounds(96, 438, 454, 28);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Classificação Indicativa");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(96, 484, 157, 17);

        txtClassfi.setBackground(new java.awt.Color(51, 51, 51));
        txtClassfi.setForeground(new java.awt.Color(255, 255, 255));
        txtClassfi.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 1, true));
        txtClassfi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtClassfiActionPerformed(evt);
            }
        });
        jPanel1.add(txtClassfi);
        txtClassfi.setBounds(96, 507, 454, 28);

        btVoltar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/ulbra/img/b_back.png"))); // NOI18N
        btVoltar.setText("Cancelar");
        btVoltar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btVoltarMouseClicked(evt);
            }
        });
        btVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btVoltarActionPerformed(evt);
            }
        });
        jPanel1.add(btVoltar);
        btVoltar.setBounds(682, 626, 144, 45);

        btEscolherImagem.setBackground(new java.awt.Color(153, 153, 153));
        btEscolherImagem.setText("Escolher Imagem");
        btEscolherImagem.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btEscolherImagemMouseClicked(evt);
            }
        });
        jPanel1.add(btEscolherImagem);
        btEscolherImagem.setBounds(1174, 328, 142, 41);

        lbFoto.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.add(lbFoto);
        lbFoto.setBounds(962, 205, 200, 304);

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Nome");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(96, 219, 41, 17);

        txtCodigo.setEditable(false);
        txtCodigo.setBackground(new java.awt.Color(51, 51, 51));
        txtCodigo.setForeground(new java.awt.Color(255, 255, 255));
        txtCodigo.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 1, true));
        txtCodigo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCodigoActionPerformed(evt);
            }
        });
        jPanel1.add(txtCodigo);
        txtCodigo.setBounds(96, 181, 454, 28);

        btExcluir2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/ulbra/img/b_excluir.png"))); // NOI18N
        btExcluir2.setText("Excluir");
        btExcluir2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btExcluir2MouseClicked(evt);
            }
        });
        jPanel1.add(btExcluir2);
        btExcluir2.setBounds(883, 626, 145, 45);

        btAlterar.setBackground(new java.awt.Color(51, 51, 51));
        btAlterar.setForeground(new java.awt.Color(255, 255, 255));
        btAlterar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/ulbra/img/b_alterar.png"))); // NOI18N
        btAlterar.setText("Alterar");
        btAlterar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btAlterarMouseClicked(evt);
            }
        });
        btAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAlterarActionPerformed(evt);
            }
        });
        jPanel1.add(btAlterar);
        btAlterar.setBounds(482, 626, 146, 45);

        txtDescricao.setBackground(new java.awt.Color(51, 51, 51));
        txtDescricao.setColumns(20);
        txtDescricao.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        txtDescricao.setForeground(new java.awt.Color(255, 255, 255));
        txtDescricao.setLineWrap(true);
        txtDescricao.setRows(5);
        txtDescricao.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtDescricaoKeyPressed(evt);
            }
        });
        jScrollPane2.setViewportView(txtDescricao);

        jPanel1.add(jScrollPane2);
        jScrollPane2.setBounds(609, 181, 308, 354);

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Descrição");
        jPanel1.add(jLabel9);
        jLabel9.setBounds(609, 152, 65, 17);

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/ulbra/img/fundo4.jpg"))); // NOI18N
        jPanel1.add(jLabel10);
        jLabel10.setBounds(370, 0, 1000, 560);

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/ulbra/img/fundo4.jpg"))); // NOI18N
        jPanel1.add(jLabel11);
        jLabel11.setBounds(0, 0, 990, 560);

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/ulbra/img/fundo4.jpg"))); // NOI18N
        jPanel1.add(jLabel12);
        jLabel12.setBounds(0, 170, 990, 560);

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/ulbra/img/fundo4.jpg"))); // NOI18N
        jPanel1.add(jLabel13);
        jLabel13.setBounds(370, 170, 1000, 560);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1368, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
   
    private void txtNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNomeActionPerformed

    private void txtGeneroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtGeneroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtGeneroActionPerformed

    private void txtProdutoraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtProdutoraActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtProdutoraActionPerformed

    private void txtDataLanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDataLanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDataLanActionPerformed

    private void txtClassfiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtClassfiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtClassfiActionPerformed
    
    private boolean verificarCampos(){
        if(lbFoto.getIcon() == null){
            JOptionPane.showMessageDialog(null, "Campo 'Foto' em branco");
            return false;
        }
        if(txtNome.getText().equals("")){
            JOptionPane.showMessageDialog(null, "Campo 'Nome' está vázio");
            return false;
        }
        if(!txtNome.getText().matches("^[\\p{L}[0-9] ]+$")){
            JOptionPane.showMessageDialog(null, "Campo 'Nome' possui caracteres inválidos");
            return false;
        }
        if(txtGenero.getText().equals("")){
            JOptionPane.showMessageDialog(null, "Campo 'Gênero' está vázio");
            return false;
        }
        if(!txtGenero.getText().matches("^[\\p{L} ]+.*[,].*+$")){
            JOptionPane.showMessageDialog(null, "Campo 'Gênero' possui caracteres inválidos");
            return false;
        }
        if(txtProdutora.getText().equals("")){
            JOptionPane.showMessageDialog(null, "Campo 'Produtora' está vázio");
            return false;
        }
        if(!txtProdutora.getText().matches("^^[\\p{L} ]+$")){
            JOptionPane.showMessageDialog(null, "Campo 'Produtora' possui caracteres inválidos");
            return false;
        }
        if(txtDataLan.getText().equals("")){
            JOptionPane.showMessageDialog(null, "Campo 'Data Lançamento' está vázio");
            return false;
        }
        if(!txtDataLan.getText().matches("^[0-9]{2}/[0-9]{2}/[0-9]{4}$")){
            JOptionPane.showMessageDialog(null, "Campo 'Data Lançamento' possui caracteres inválidos"
                    +"\n\nEx: 01/01/2000");
            return false;
        }
        if(txtClassfi.getText().equals("")){
            JOptionPane.showMessageDialog(null, "Campo 'Classificação' está vázio");
            return false;
        }
        if(!txtClassfi.getText().matches("^[{+}0-9]{3}")){
            JOptionPane.showMessageDialog(null, "Campo 'Classificação' possui caracteres inválidos");
            return false;
        }
        if(txtDescricao.getText().equals("")){
            JOptionPane.showMessageDialog(null, "Campo 'Descrição' está vázio");
            return false;
        }
       
        return true;
    }
    
    private void btVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btVoltarActionPerformed
        this.dispose();
    }//GEN-LAST:event_btVoltarActionPerformed

    private void btEscolherImagemMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btEscolherImagemMouseClicked
        JFileChooser fileChooser = new JFileChooser();
        fileChooser.setDialogTitle("Escolha um arquivo");

        int returnValue = fileChooser.showOpenDialog(null);

        if(returnValue == JFileChooser.APPROVE_OPTION){
            File arquivo = fileChooser.getSelectedFile();
            Icon icon = Utils.fileParaIcon(arquivo);

            ImageIcon iconRedimensionado = Utils.redimensionarIcon (
                icon, 200, 300);

            lbFoto.setIcon(iconRedimensionado);
        }
    }//GEN-LAST:event_btEscolherImagemMouseClicked

    private void txtCodigoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCodigoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCodigoActionPerformed

    private void btExcluir2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btExcluir2MouseClicked
        int resposta = JOptionPane.showConfirmDialog(null, "Deseja excluir o jogo?",
            "Confirmação", JOptionPane.YES_NO_OPTION);

        if(resposta == JOptionPane.YES_OPTION){
            JogoController controller = new JogoController();
            if(controller.excluirJogo(pkJogo)){
                this.dispose();
            }
        }
    }//GEN-LAST:event_btExcluir2MouseClicked

    private void btAlterarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btAlterarMouseClicked
        
    }//GEN-LAST:event_btAlterarMouseClicked

    public void carregar(){
        JogoController controller = new JogoController();
        Jogo jg = controller.readForPk(pkJogo);

        String codigo = String.valueOf(jg.getPk_jogo());
        txtCodigo.setText(codigo);
        txtNome.setText(jg.getNomeJogo());
        txtGenero.setText(jg.getGeneroJogo());
        txtProdutora.setText(jg.getProdutoraJogo());
        txtDataLan.setText(jg.getDataLanJogo());
        txtClassfi.setText(jg.getClassfiJogo());
        txtDescricao.setText(jg.getDescricaoJogo());
        lbFoto.setIcon(jg.getImagemJogo());
    }
    
    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        
        
        
    }//GEN-LAST:event_formWindowActivated

    private void btVoltarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btVoltarMouseClicked
       
    }//GEN-LAST:event_btVoltarMouseClicked

    private void txtDescricaoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtDescricaoKeyPressed

    }//GEN-LAST:event_txtDescricaoKeyPressed

    private void btAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAlterarActionPerformed
       if(!verificarCampos()){
            return;
        }
        
        JogoController controller = new JogoController();
        Jogo jogo = new Jogo();
        
        jogo.setPk_Jogo(pkJogo);
        jogo.setNomeJogo(txtNome.getText());
        jogo.setGeneroJogo(txtGenero.getText());
        jogo.setProdutoraJogo(txtProdutora.getText());
        jogo.setDataLanJogo(txtDataLan.getText());
        jogo.setClassfiJogo(txtClassfi.getText());
        jogo.setDescricaoJogo(txtDescricao.getText());
        jogo.setImagemJogo(lbFoto.getIcon());

        if(controller.alterarJogo(jogo)){
        this.dispose();
        }
    }//GEN-LAST:event_btAlterarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FRUpDelJogo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FRUpDelJogo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FRUpDelJogo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FRUpDelJogo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                FRUpDelJogo dialog = new FRUpDelJogo(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btAlterar;
    private javax.swing.JButton btEscolherImagem;
    private javax.swing.JButton btExcluir2;
    private javax.swing.JButton btVoltar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lbFoto;
    private javax.swing.JTextField txtClassfi;
    private javax.swing.JTextField txtCodigo;
    private javax.swing.JTextField txtDataLan;
    private javax.swing.JTextArea txtDescricao;
    private javax.swing.JTextField txtGenero;
    private javax.swing.JTextField txtNome;
    private javax.swing.JTextField txtProdutora;
    // End of variables declaration//GEN-END:variables
}
